const topics=[
['About Find My Local','A trusted place where people, local knowledge and everyday needs meet. Find help close to home or wherever your journey takes you.','Community network','Connected communities'],
['The Problem We Are Solving','Finding dependable local assistance can be uncertain, time-consuming and stressful—especially in a new place or urgent situation.','Search with confidence','Trusted help nearby'],
['What is Find My Local?','One human-first platform for finding verified local helpers, sharing requirements and building safer connections within communities.','Your local ecosystem','Help • chat • location'],
['How Find My Local Works','Search or post a requirement, discover nearby verified helpers, agree service details, complete the work and review the experience.','USER ↔ HELPER','Six simple steps'],
['Users','Whether you are travelling, studying, caring for family or settling somewhere new, local support should be easy to reach.','Traveler • Student','Family • Professional'],
['Helpers','Local people can share their skills and knowledge—from guidance and translation to elder support, tourism and accommodation.','Available helpers','Skills that matter'],
['Major Features','A connected feature ecosystem brings discovery, work, emergencies, communication, payments, reviews and agreements together.','FIND MY LOCAL','Everything connected'],
['Verified Local Helpers','A thoughtful verification journey can include live selfie, government ID and residency proof before a helper becomes discoverable.','IDENTITY VERIFIED','Live selfie • ID • Proof'],
['Smart Helper Discovery','Discover relevant nearby helpers by location, skills, ratings, distance, service, language and verification status.','NEARBY NOW','Location • Skills • Ratings'],
['Post a Work','Post what you need, notify relevant nearby helpers, receive interest and choose who to connect with.','POST → MATCH → CONNECT','Local opportunities'],
['Service Commitment Forms','Keep service details, date and time, pricing, notes and terms clear with a digital commitment form.','SERVICE AGREEMENT','Clear expectations'],
['Community Trust System','Trust grows through verification, reviews, completed tasks, ratings and meaningful participation in the community.','TRUST SCORE','Reviews • badges • ratings'],
['Emergency Alert System','An emergency alert can expand from village to town, district and state—reaching nearby community nodes quickly.','EMERGENCY ALERT','Village → State'],
['Secure Communication','Communicate confidently through chat, voice, media, live location, payment requests and notifications.','SECURE CHANNEL','Chat ↔ Voice ↔ Location'],
['Payment System','Use clear, secure payment details such as UPI, QR and bank information without imitating any specific payment interface.','SECURE PAYMENT','UPI • QR • Bank'],
['Helper Gallery','Explore work photos, accommodation photos, local-area images and previous service experiences before you connect.','LOCAL STORIES','Photos with context'],
['Dual Account Mode','One phone number can support both roles, letting a person switch smoothly between User Mode and Helper Mode.','USER ↕ HELPER','One account, two roles'],
['Security Features','Layered safety includes biometric app lock, Face ID, fingerprint, OTP, single-device login, secure storage and role-based access.','PROTECTED','Shield • OTP • Biometrics'],
['How Find My Local Helps India','Trusted communities, local employment, safer travel, emergency support, tourism and newcomer assistance can grow from connected local networks.','INDIA, CONNECTED','Village → Town → City'],
['Target Audience','Built for travelers, tourists, students, professionals, families, elderly citizens, NGOs, businesses, event organizers and rural communities.','FOR EVERYONE','People & communities'],
['Vision','To become India’s most trusted hyperlocal community platform by connecting every person with verified local assistance anytime, anywhere.','OUR VISION','A trusted India-wide network'],
['Mission','To empower local communities, create meaningful earning opportunities, and make trusted human assistance accessible across every village, town, city, and state in India.','OUR MISSION','Communities that grow together'],
['Why Find My Local is Different','Hyperlocal discovery, verified helpers, work marketplace, emergency alerts, communication, agreements, trust, payments and India-wide support—unified in one platform.','ONE LOCAL PLATFORM','Everything local, connected']
];
const slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const grid=document.querySelector('#topicGrid'),sections=document.querySelector('#topicSections');
topics.forEach(([title,copy,core,a,b],i)=>{const id=slug(title);grid.insertAdjacentHTML('beforeend',`<a class="topic-card" href="#${id}"><span>${String(i+1).padStart(2,'0')}</span><b>${title}</b><span>Explore →</span></a>`);sections.insertAdjacentHTML('beforeend',`<section id="${id}" class="story section" style="--accent:${['#08a6b5','#4dbd4d','#0865c7'][i%3]};--bg:${i%2?'#f3fbff':'#eafff8'}"><div class="story-copy reveal"><p class="eyebrow">${String(i+1).padStart(2,'0')} / Find My Local</p><h2>${title}</h2><p>${copy}</p><ul><li>${a}</li><li>${b}</li><li>Designed around trusted local connection</li></ul></div><div class="story-visual reveal" aria-label="Animated illustration for ${title}"><div class="visual-core">${core}</div><span class="orbit-item">Verified</span><span class="orbit-item">Nearby</span><span class="orbit-item">Connected</span><span class="orbit-item">Trusted</span><i class="network-dot" style="top:23%;left:32%"></i><i class="network-dot" style="bottom:26%;right:29%"></i></div></section>`)});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.13});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('nav');toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',open);toggle.textContent=open?'×':'☰'});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');toggle.setAttribute('aria-expanded','false');toggle.textContent='☰'}));
addEventListener('scroll',()=>document.querySelector('.site-header').classList.toggle('scrolled',scrollY>10),{passive:true});
let rating=0;document.querySelectorAll('.stars button').forEach(button=>button.addEventListener('click',()=>{rating=+button.dataset.rating;document.querySelectorAll('.stars button').forEach(b=>{b.classList.toggle('active',+b.dataset.rating<=rating);b.setAttribute('aria-checked',+b.dataset.rating===rating)})}));
document.querySelector('#feedbackForm').addEventListener('submit',e=>{e.preventDefault();document.querySelector('#formNote').textContent='Thank you. Your feedback is ready to be connected to the website’s backend.';e.target.reset();rating=0;document.querySelectorAll('.stars button').forEach(b=>b.classList.remove('active'))});
